### PR TITLE
Update forgejo 1.20.4 --> 1.20.5

### PR DESCRIPTION
**Pull request by jahanson**
Just released https://codeberg.org/forgejo/forgejo/releases/tag/v1.20.5-0

### CODE REVIEW

**Comment by jahanson** [comment]
@NeonMinnen new version is out, can we get this updadated? :)

**Comment by jahanson** [comment]
I've just resumed updating the version in my vars.yml with `forgejo_version: 1.20.5-0` I'll close this pull request if it's not needed.

**Comment by mattredact** [comment]
Sorry about the delay. The role is back to being updated. Was on a hiatus.

**Comment by jahanson** [comment]
@NeonMinnen I've updated the default value to the latest version.

**Comment by mattredact** [comment]
> @NeonMinnen I've updated the default value to the latest version.

Hi!
Thanks for the PR. I updated the role to the latest version a few hours ago and it's been merged with https://github.com/mother-of-all-self-hosting/mash-playbook

**Comment by jahanson** [comment]
Alright, thank you for your work :) I'll close this then.

**Pull request closed without merging**
